[package]
name = "gpt_tokenizer"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1"




[dependencies]
flutter_rust_bridge = "1"
fancy-regex = "0.11.0"
regex = "1.7.0"
rustc-hash = "1.1.0"
bstr = "1.0.1"

anyhow = {  features = ["backtrace"] }